name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_AI_AGENT_URL: ${{ vars.NEXT_PUBLIC_AI_AGENT_URL }}
  NEXT_PUBLIC_INFERENCEAI_POST_CHATS_WEBHOOK: ${{ vars.NEXT_PUBLIC_INFERENCEAI_POST_CHATS_WEBHOOK }}
  NEXT_PUBLIC_INFERENCEAI_GET_CHATS_WEBHOOK: ${{ vars.NEXT_PUBLIC_INFERENCEAI_GET_CHATS_WEBHOOK }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build and export
        run: bun run build
        env:
          NEXT_PUBLIC_AI_AGENT_URL: ${{ vars.NEXT_PUBLIC_AI_AGENT_URL }}
          NEXT_PUBLIC_INFERENCEAI_POST_CHATS_WEBHOOK: ${{ vars.NEXT_PUBLIC_INFERENCEAI_POST_CHATS_WEBHOOK }}
          NEXT_PUBLIC_INFERENCEAI_GET_CHATS_WEBHOOK: ${{ vars.NEXT_PUBLIC_INFERENCEAI_GET_CHATS_WEBHOOK }}

      - name: Create CNAME file
        run: echo "hyperjump.tech" > out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
